list_languages = ('python',
                  'ruby',
                  'haskell',
                  'c',
                  'java',
                  'html',
                  'go',
                  'bash',
                  'perl',
                  'javascript',
                  )
